// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx_-NoQRpiqg7aqLKyLMDt6WAbOBOkx8w',
    appId: '1:262571734333:web:52bf02788a00f558274154',
    messagingSenderId: '262571734333',
    projectId: 'thort-jivit',
    authDomain: 'thort-jivit.firebaseapp.com',
    storageBucket: 'thort-jivit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm4m_-KnrT8kZ_Jwe-Yh6IUeUMyNOedm8',
    appId: '1:262571734333:android:91a037240c1b38c3274154',
    messagingSenderId: '262571734333',
    projectId: 'thort-jivit',
    storageBucket: 'thort-jivit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9omoX3biH-yo1PodNHteXVM2GYNswS4Q',
    appId: '1:262571734333:ios:425349e073cfdc84274154',
    messagingSenderId: '262571734333',
    projectId: 'thort-jivit',
    storageBucket: 'thort-jivit.firebasestorage.app',
    iosBundleId: 'com.example.thortJivit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9omoX3biH-yo1PodNHteXVM2GYNswS4Q',
    appId: '1:262571734333:ios:425349e073cfdc84274154',
    messagingSenderId: '262571734333',
    projectId: 'thort-jivit',
    storageBucket: 'thort-jivit.firebasestorage.app',
    iosBundleId: 'com.example.thortJivit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx_-NoQRpiqg7aqLKyLMDt6WAbOBOkx8w',
    appId: '1:262571734333:web:1107e46d809996ef274154',
    messagingSenderId: '262571734333',
    projectId: 'thort-jivit',
    authDomain: 'thort-jivit.firebaseapp.com',
    storageBucket: 'thort-jivit.firebasestorage.app',
  );
}
